### ISSUE TITLE
Q about bsm_vega?

### ISSUE THREAD

**Issue by kechan** [yhilpisch/py4fi#1]
If I understand it right, the Vega of an option, the derivative of the norm cdf is needed. The notation you used in your book is N'(d_1), with a prime. The calculation in bsm_vega has used:

     stats.norm.cdf( ) 

which doesn't appear to be correct. Shouldn't this be just the norm pdf? ie. exp(-x^2) normalized?

**Comment by yhilpisch** [comment]
Thanks for pointing this out. It is corrected now to pdf (instead of cdf). Numerical results for implied vols do not change.

**Comment by kechan** [comment]
Sure, for this case, it may only affect the rate of numerical convergence. As long as your vega has the same sign, the {x_i} should be attracted towards the zero even if you have used the cdf instead.

Thanks for your swift response.
