### ISSUE TITLE
Example in 6.4 not working ( Netfonds's API )

### ISSUE THREAD

**Issue by tnlin** [yhilpisch/py4fi#2]
The API seems not working. I wonder whether I've got it wrong? 
This is URL I get from frombook, but the page is empty 
http://hopey.netfonds.no/posdump.php?date=20140922&paper=AAPL.O&csv_format=csv

This is URL I get from IPython. No data, only column name
http://www.netfonds.no/quotes/posdump.php?date=20140922&paper=NKE.N&csv_format=csv

Do anyone figure out the solution ?

**Comment by yhilpisch** [comment]
They only provide data for a couple of days backwards. You need to change the date(s) for which to receive the data (i.e. for some date(s) in the last two weeks) -- as commented in the Jupyter Notebook.
